### ISSUE TITLE
Feature request: should close with esc key

### ISSUE THREAD

**Issue by andreslucena** [nikku/jquery-bootstrap-scripting#18] opened 2011-09-26 18:39 UTC
Most modals have 3 ways to close: 
- Clicking outside (OK)
- Clicking in close button (OK)
- Pressing esc key (KO)

So, it would be a nice feautre to have.

**Comment by nikku** [comment] 2011-09-26 21:44
Seems to be a duplicate of #11.

**Closed as completed** 2011-09-26 21:44 UTC

**Comment by andreslucena** [comment] 2011-09-27 06:43
woop, sorry about that. It seems and it is. Keep up with the magic :)
